gene_list: "howler_specific_SV_genes.bed"
alignment_dir: "results/alignments"
figure_dir: "results/visualizations"
window_size: 50

outgroup:
    directory: "/u/project/goldberg/dmassey/howler_SV/genomes"
    human: "GCF_000001405.40_GRCh38.p14_genomic.fna"
    chimp: "GCF_028858775.2_NHGRI_mPanTro3-v2.0_pri_genomic.fna"
    gorilla: "GCA_029281585.2_NHGRI_mGorGor1-v2.0_pri_genomic.fna"
    orangutan: "GCF_028885655.2_NHGRI_mPonAbe1-v2.0_pri_genomic.fna"
    macaque: "GCF_037993035.1_T2T-MFA8v1.0_genomic.fna"
    marmoset: "GCF_011100555.1_mCalJa1.2.pat.X_genomic.fna"

howlers:
    directory: "/u/project/goldberg/shared/data/howler_assemblies"
    3273: "A_belzebul_3273_HM.cleaned.fa"
    AU1: "A_belzebul_AU1_HM.cleaned.fa"
    NG1520: "A_belzebul_NG1520_HM.cleaned.fa"
    caraya: "A_caraya_F.xuxa_HM.cleaned.fa"
    guariba: "A_guariba_3636_HM.cleaned.fa"
    seniculus: "A_seniculus_2397_HM.cleaned.fa"
